sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        OGuDGFb4yWol3WcrcqBqFK3y0BgySI+dke50Kg0M/97nf35BN9zTj+HDoF5kEJeqYC/wSWBFDg36H67fWo0VnT7mNFiMuw67hCHjU1/hNQfCDTSpQpUepeUxjdiaHYh7PFeKHv3MowrIG4l2hGN7xcmc6opKIewwZwtFXcjc0S/KxZ5JSc37+ALmFx8cZr1ePcGY1FrN/wfF5052RmbXN9Ifgq4YmVj0qFNTiFmcW9HGx8nDjf6BqYfFMPkwatOAdjqBK6y7A7gfyD3yuNlB1E5jlcEwWTY+lf1Z8qgrv1pB0h36IkwILMecwddiiJH4hnXz/pA99X1x8x2lH8KteX5Cfp2Ntem6SWl0fMjUzyQr87RGCnhPkH693xuLY3RPjgGyfeLoBNAuMEUvIDwFXSybTrYL4s5PFBPLAFuiqBKAGeYIGY8q9/fq0FIIUns763JtGjnKdJJfgf87/8pCNS8nA7KEEDR8aY6aH73BtVdtuDdAsCHnLtOZmrgR8zyMmqoye7ZgVXL4y8iPUDOt671vFsXJm+i59c/z3LFZfEcMVUCjJUwAct5ty1N2T58ooY+Xq1Ib/z6ulf4HGAN51CUWGL9XvR+CUoMSfC7qOYkAvtrnIdnkbsKMsWvZnkGB6FAF0wHoTDIFKac+E0ueS9RpdBnHgAnJ/AicxsnhYCo=
    - secure: >-
        VT1DhqpMA1YTDMLaC2auzqAoxcVFhukYY1IAGHsNouJpD3MYutqgSXVEzvLc0qEBDq3U/nVUidcIuWpIIAo04LX8g7MAv+PY8vBryTjGRGeZyOThvrHCxpwSs3eODaKF54NGgT5RORZ8cxMpE4x37athztOaccMhNjfWwQUBX6FTeo9PAMCIIlBp3k/73B0lcJJkVCtp+Gv2A7iSm2ivaHGepmS/fv6kj5fysC5YKdBlB9YVS8+APhrhR7CDMwbLtJMwDfEAkhbrvxxqj6o+jUKPc71OkiqqE4BCIwWgXWKyZ1wuIFQnaM4dMVawnWCKlUMlIb15EcoWvNxxoSlGJlv62IoIsDIBNQXw+TwvxORbdsvlDcwPT4W+95xvX/HZdukIdq7SkBGHIWci73YWI+s6pJHZJ267thmkgH20xkXNrrm1peVZwXuLbXp3EdawsuA0kEVuSw3/xmNbRqz5borPz6KALLP3KG6elAfk+9/aOF0sqln6bQIDBnh91dpOFeU3GxMx8HK8jQ0iC71Lr1a9Sdr4a+xQPDdMRvjqnsycrdW2+VcpLEi/Vrsh3MmURowJFqapgJR272aWy2a3khToGywihM58/wi069lZ7xHrXMbnThLeSzak+UrIIaqxhFqaqUorMSMRL2LUb7WeAwD99YotWbD0kTe7KGUz+bI=
script:
  - npm run test
notifications:
  webhooks: 'http://testhook.javascript.ru/automation/ci/build'
