sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        BU/Pb6gIrIkcKy5aoAi8nqLCpCIB51Qm9S8mElHTKgd7SR/BC6SuJnaqKikmW088ew79Utd8tUZKnk+Kg8K0Y4NHsZvJ4rTAsQ9Oi1gN48JiXK6SAqIPE4zmLg35MglhXeNtKhP8tGNo6cCv23Dj75s5eiZvw9HVXJwCCppsuNs6hUIEpFftbBoH0BGo9+tbKeS02pt8BOOSFTCa/ToSWssAK51Nhzxmp5lGY1HAec5ID4xxhO6Oy7ZlP/a+tckTxBohCG/m3nMcwqwYmUr8X47Axcfvzyt/9ikdTAplkELSFmkDaEgzUB2/fznC+iDW24Sp23V4CL+tYhw/HTE7uQJvp2jbI57YkQRnvh0COT8EccVJEI6/CmvfyjloOrg7MePYbEOPYSFZxaIY4aWk0qebMt3tyNUv3DKXdqF8EZO+jG/D1sEBlJnpZrFAiZrmFfqVP5GKiQrVnXl+brd0Wyr2n2pH6qVpLD7ZfgdR94pDW/fgEriyoKY6DB9K/I5xERYI+nxdrpv6r76BUJnlUkUUMXYf3+kRDlNsXbUMQlMS0svihbQ4JaJWsLinUiGKp7DiUc2u5IchKv+uI9T4HsnGX2+jeJNZ7KhUtXR/foPoZ7fNZT9iNyVWxcVYejZ9A2ekSI7yiMvO168Xa2mo8lhsEkOBdpzVu3G+jEv8TSw=
    - secure: >-
        ptrl6ioS7/8nU97J+wUdcSQSIOo2esARufo7XfDCWzycNUzN9HL8Sz+k5C/hH9EURv7oI6NsDIUAfZh6e2DMohduLi6ZXhqi+1L5HFlLaCijCUyJi9drP5TZMpHUneMJyBOTyyAiPczzNlEe0Hv3ZvqeEQg4rBcBigfZJCzGskRFmeDaJBLKs59DMpD5NedExbUhvqYsmf8ITpSew3ltlzyNqFHBkJWJ5lioabX6lwrzdhlfSrLw8XJ7lj+lpRRx6aCxrqLBz3ao6jd1D1YVNApOilMvOY72rk3hCQlB9ZRivHO5IBL08Jt6VWxqJ0b1+ipVWl5k+p34qne8AN+qG1zbMVD93zhRH1HTcpS0sspqOhGBC5gcTEysKP/n7eZXQ6JRA42+7/LcAzWtSYaxnS4ZeZ0S06vTMUEp1FAUb1oEkKaOTollb9xoDnNubbrD7Ps8V0TiJ/jVrJw9MRANxgN9ClzvMzDC8HUwEhlzohB/vgbkJY0Tqk5u/jyuuQKlIM3iyqt0UwrmQTXEuLX+DK//UEmrpDY4zsHTU7onU/59BkIYB8RV+ws3JK7zPb8TlvjToivYHXiFUzEfcLrOXAVaBAl1HZn378nu39dh609NbcLBBCqE8MsrTvainTZ+2+J0y1qfu/AhNvCMfS+jmJKvr+WLY2rKY4O4An0WsC0=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
